//Product Types
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'


// Prodect Details types
export const PRODUCT_DETAILES_REQUEST = 'PRODUCT_DETAILES_REQUEST'
export const PRODUCT_DETAILES_SUCCESS = 'PRODUCT_DETAILES_SUCCESS'
export const PRODUCT_DETAILES_FAIL = 'PRODUCT_DETAILES_FAIL'

// ADD/Remove Product in cart Types
export const CART_ADD_ITEM= 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_RESET_ITEMS = 'CART_RESET_ITEMS'

//User Login/logout
export const  USER_LOGIN_REQUEST ="USER_LOGIN_REQUEST" 
export const  USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS" 
export const  USER_LOGIN_FAIL ="USER_LOGIN_FAIL" 
export const  USER_LOGOUT ="USER_LOGOUT" 

//User Register
export const  USER_REGISTER_REQUEST ="USER_REGISTER_REQUEST" 
export const  USER_REGISTER_SUCCESS ="USER_REGISTER_SUCCESS" 
export const  USER_REGISTER_FAIL ="USER_REGISTER_FAIL" 

//User Register
export const  USER_DETAILES_REQUEST ="USER_DETAILES_REQUEST" 
export const  USER_DETAILES_SUCCESS ="USER_DETAILES_SUCCESS" 
export const  USER_DETAILES_FAIL ="USER_DETAILES_FAIL" 
export const  USER_DETAILES_RESET ="USER_DETAILES_RESET" 


//Profile Update
export const  USER_UPDATE_PROFILE_REQUEST ="USER_UPDATE_PROFILE_REQUEST" 
export const  USER_UPDATE_PROFILE_SUCCESS ="USER_UPDATE_PROFILE_SUCCESS" 
export const  USER_UPDATE_PROFILE_FAIL ="USER_UPDATE_PROFILE_FAIL" 

// Shipping/payment 
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"

//Create Order 

export const  ORDER_CREATE_REQUEST ="ORDER_CREATE_REQUEST" 
export const  ORDER_CREATE_SUCCESS ="ORDER_CREATE_SUCCESS" 
export const  ORDER_CREATE_FAIL ="ORDER_CREATE_FAIL" 

//Create Order 
export const  ORDER_DETAILS_REQUEST ="ORDER_DETAILS_REQUEST" 
export const  ORDER_DETAILS_SUCCESS ="ORDER_DETAILS_SUCCESS" 
export const  ORDER_DETAILS_FAIL ="ORDER_DETAILS_FAIL" 
// Order payment Actions
export const  ORDER_PAY_REQUEST ="ORDER_PAY_REQUEST" 
export const  ORDER_PAY_SUCCESS ="ORDER_PAY_SUCCESS" 
export const  ORDER_PAY_FAIL ="ORDER_PAY_FAIL" 
export const  ORDER_PAY_RESET = "ORDER_PAY_RESET" 

//Get My Orders List 
export const  My_ORDER_LIST_REQUEST ="My_ORDER_LIST_REQUEST" 
export const  My_ORDER_LIST_SUCCESS ="My_ORDER_LIST_SUCCESS" 
export const  My_ORDER_LIST_FAIL ="My_ORDER_LIST_FAIL" 
export const  My_ORDER_LIST_RESET ="My_ORDER_LIST_RESET" 

//All users 
export const  USER_LIST_REQUEST ="USER_LIST_REQUEST" 
export const  USER_LIST_SUCCESS ="USER_LIST_SUCCESS" 
export const  USER_LIST_FAIL ="USER_LIST_FAIL" 
export const  USER_LIST_RESET ="USER_LIST_RESET" 
//Delete users 
export const  USER_DELETE_REQUEST ="USER_DELETE_REQUEST" 
export const  USER_DELETE_SUCCESS ="USER_DELETE_SUCCESS" 
export const USER_DELETE_FAIL = "USER_DELETE_FAIL" 
//Update user list
export const  USER_UPDATE_REQUEST ="USER_UPDATE_REQUEST" 
export const  USER_UPDATE_SUCCESS ="USER_UPDATE_SUCCESS" 
export const  USER_UPDATE_FAIL ="USER_UPDATE_FAIL" 
export const  USER_UPDATE_RESET ="USER_UPDATE_RESET" 

//Delete Product 
export const  PRODUCT_DELETE_REQUEST ="PRODUCT_DELETE_REQUEST" 
export const  PRODUCT_DELETE_SUCCESS ="PRODUCT_DELETE_SUCCESS" 
export const  PRODUCT_DELETE_FAIL ="PRODUCT_DELETE_FAIL" 
//Create Product 
export const  PRODUCT_CREATE_REQUEST ="PRODUCT_CREATE_REQUEST" 
export const  PRODUCT_CREATE_SUCCESS ="PRODUCT_CREATE_SUCCESS" 
export const  PRODUCT_CREATE_FAIL ="PRODUCT_CREATE_FAIL" 
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET" 

//Update Product list
export const  PRODUCT_UPDATE_REQUEST ="PRODUCT_UPDATE_REQUEST" 
export const  PRODUCT_UPDATE_SUCCESS ="PRODUCT_UPDATE_SUCCESS" 
export const  PRODUCT_UPDATE_FAIL ="PRODUCT_UPDATE_FAIL" 
export const  PRODUCT_UPDATE_RESET ="PRODUCT_UPDATE_RESET" 


