//Product Types
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'


// Prodect Details types
export const PRODUCT_DETAILES_REQUEST = 'PRODUCT_DETAILES_REQUEST'
export const PRODUCT_DETAILES_SUCCESS = 'PRODUCT_DETAILES_SUCCESS'
export const PRODUCT_DETAILES_FAIL = 'PRODUCT_DETAILES_FAIL'

// ADD/Remove Product in cart Types
export const CART_ADD_ITEM= 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

//User Login/logout
export const  USER_LOGIN_REQUEST ="USER_LOGIN_REQUEST" 
export const  USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS" 
export const  USER_LOGIN_FAIL ="USER_LOGIN_FAIL" 
export const  USER_LOGOUT ="USER_LOGOUT" 

//User Register
export const  USER_REGISTER_REQUEST ="USER_REGISTER_REQUEST" 
export const  USER_REGISTER_SUCCESS ="USER_REGISTER_SUCCESS" 
export const  USER_REGISTER_FAIL ="USER_REGISTER_FAIL" 

//User Register
export const  USER_DETAILES_REQUEST ="USER_DETAILES_REQUEST" 
export const  USER_DETAILES_SUCCESS ="USER_DETAILES_SUCCESS" 
export const  USER_DETAILES_FAIL ="USER_DETAILES_FAIL" 


//Profile Update
export const  USER_UPDATE_PROFILE_REQUEST ="USER_UPDATE_PROFILE_REQUEST" 
export const  USER_UPDATE_PROFILE_SUCCESS ="USER_UPDATE_PROFILE_SUCCESS" 
export const  USER_UPDATE_PROFILE_FAIL ="USER_UPDATE_PROFILE_FAIL" 

// Order Actions
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"

